#!/usr/bin/env python
import numpy as np
import matplotlib.pylab as mpl
import verif.input
import verif.data
import verif.field
import netCDF4
import argparse

def main():
   parser = argparse.ArgumentParser(prog="text2verif", description="Convert text to netcdf verif files")
   parser.add_argument('files', nargs="*")
   args = parser.parse_args()

   if len(args.files) != 2:
      verif.util.error("Need exactly 2 input files")

   input = verif.input.get_input(args.files[0])
   times = input.times
   leadtimes = input.leadtimes
   locations = input.locations
   variable = input.variable
   print times - times[0]

   output = netCDF4.Dataset(args.files[1], 'w')
   output.createDimension("time", None)
   output.createDimension("leadtime", len(leadtimes))
   output.createDimension("location", len(locations))
   vTime=output.createVariable("time", "i4", ("time",))
   vOffset=output.createVariable("leadtime", "f4", ("leadtime",))
   vLocation=output.createVariable("location", "i4", ("location",))
   vLat=output.createVariable("lat", "f4", ("location",))
   vLon=output.createVariable("lon", "f4", ("location",))
   vElev=output.createVariable("altitude", "f4", ("location",))
   vfcst=output.createVariable("fcst", "f4", ("time", "leadtime", "location"))
   vobs=output.createVariable("obs", "f4", ("time", "leadtime", "location"))
   output.standard_name = variable.name
   output.units = unit = variable.units

   vobs[:] = input.obs
   vfcst[:] = input.fcst
   vTime[:] = input.times
   vOffset[:] = input.leadtimes
   vLocation[:] = [s.id for s in locations]
   vLat[:] = [s.lat for s in locations]
   vLon[:] = [s.lon for s in locations]
   vElev[:] = [s.elev for s in locations]
   output.Conventions = "verif_1.0.0"
   output.close()


if __name__ == '__main__':
   main()
